### ISSUE TITLE
Strings not logged correctly

### ISSUE THREAD

**Issue by nporter-adbe** [adobe/aepsdk-core-ios#519] opened 2021-01-20 19:01 UTC
When printing shared state and other event data to the logging service it appears that occasionally quotation marks are left out when printing these values. I double-checked in the debugger and `mid` is a `String`, however, it prints as if it's an `Int`.

```
2021-01-19 14:13:31.943096-0800 School App AEP[13386:362144] [AEP SDK DEBUG - <EventHub>] Shared state created for com.adobe.module.identity with version 0 and data: 
{
  blob = j8Odv6LonN4r3an7LhD3WZrU1bUpAkFkkiY1ncBR96t2PTI;
  lastsync = "1611082533.758741";
  locationhint = 9;
  mid = 65837975888089377005040020619800013833;
}
```

**Comment by yangyansong-adbe** [comment] 2021-02-04 01:59
This is as expected in Swift, since we're printing `event data` as an `AnyObject`.
https://github.com/adobe/aepsdk-core-ios/blob/07423d952bef7bacaaac98ea1abc0e76e783107a/AEPCore/Sources/eventhub/EventHub.swift#L184

See my sample code and output => 

```Swift
var dict = [String: Any]()
dict = [
    "a": "13435454",
    "b":[
        "b1": 1235566,
        "b2": "35566"
    ]
]
print(dict as AnyObject)
print(dict)
```

```
{
    a = 13435454;
    b =     {
        b1 = 1235566;
        b2 = 35566;
    };
}
["a": "13435454", "b": ["b2": "35566", "b1": 1235566]]
```

**Comment by yangyansong-adbe** [comment] 2021-02-04 22:53
@nporter-adbe I think this is not a bug, can we close it?

**Comment by nporter-adbe** [comment] 2021-02-04 23:27
It may not be a bug exactly, but the logs are misleading. The reason I originally opened this issue is that someone asked why we were sharing the mid as a number in Swift. In the original log, I posted it looks like the mid is a number and not a string. 

I think it'd be best if the logs accurately portrayed the data types of the values being printed. My suggestion would be to potentially serialize the event data as pretty-printed JSON, then print it. If serialization fails, just print it as `Any`.

**Closed** 2021-03-16 19:39 UTC
Labels: coresquad, enhancement
